version: '2'
services:
  concesionario-app:
    image: concesionario
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://concesionario-mysql:3306/concesionario?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://concesionario-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://concesionario-elasticsearch:9200
    ports:
      - 8080:8080
  concesionario-mysql:
    extends:
      file: mysql.yml
      service: concesionario-mysql
  concesionario-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: concesionario-elasticsearch
